version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: install modules
          command: npm i
      - run:
          name: eslint
          command: npm run lint
