version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: npm run test
          command: npm run test
      - run:
          name: npm run lint
          command: npm run lint
      - run:
          name: npm run build
          command: npm run build
      - run:
          name: npm prune -production
          command: npm prune -production
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: login Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: npm run docker-build
          command: npm run docker-build
